FROM python:3.13-slim 

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        libssl-dev \
        pkg-config \
        libasound2-dev \
        cargo && \
    rm -rf /var/lib/apt/lists/*

RUN cargo install librespot
RUN export PATH=$PATH:/root/.cargo/bin

COPY . /bot 
WORKDIR /bot 
RUN pip install -r requirements.txt

CMD ["python", "bot.py"]
