FROM giof71/librespot:latest as librespot

FROM python:3.13-slim 

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg && \
    rm -rf /var/lib/apt/lists/*

COPY --from=librespot /usr/bin/librespot /usr/bin/librespot
COPY . /bot 
WORKDIR /bot 
RUN pip install -r requirements.txt

CMD ["python", "bot.py"]
